import images from './images'

export const contacts = [
    {
        id: '1',
        userName: 'Phòng khám đa khoa Hùng Dũng',
        userImg: images.user1,
        isOnline: false,
        lastSeen: '3 Days ago',
        lastMessage: 'How is it going...',
        messageInQueue: 3,
        sentDate: '12/7',
    },
    {
        id: '2',
        userName: 'Phòng khám An Bình',
        userImg: images.user2,
        isOnline: true,
        lastSeen: 'Online',
        lastMessage: 'Good morning...',
        messageInQueue: 0,
        sentDate: '12/7',
    },
    {
        id: '3',
        userName: 'Phòng khám Lucia Mu',
        userImg: images.user3,
        isOnline: false,
        lastSeen: '2 weeks ago',
        lastMessage: "What's up...",
        messageInQueue: 0,
        sentDate: '12/7',
    },
    {
        id: '4',
        userName: 'Phòng khám Raki Lili',
        userImg: images.user4,
        isOnline: true,
        lastSeen: 'Online',
        lastMessage: 'Send me the link',
        messageInQueue: 0,
        sentDate: 'Today',
    },
    {
        id: '5',
        userName: 'Phòng khám Raki Devine',
        userImg: images.user5,
        isOnline: false,
        lastSeen: '5 days ago',
        lastMessage: 'We are doing...',
        messageInQueue: 0,
        sentDate: '23/9',
    },
    {
        id: '6',
        userName: 'Phòng khám Aris Yup',
        userImg: images.user6,
        isOnline: true,
        lastSeen: 'Online',
        lastMessage: 'How is it going...',
        messageInQueue: 3,
        sentDate: 'Today',
    },
    {
        id: '7',
        userName: 'Phòng khám Aris Yup',
        userImg: images.user6,
        isOnline: true,
        lastSeen: 'Online',
        lastMessage: 'How is it going...',
        messageInQueue: 3,
        sentDate: '12/7',
    },
    {
        id: '8',
        userName: 'Phòng khám Billy Di',
        userImg: images.user2,
        isOnline: true,
        lastSeen: 'Online',
        lastMessage: 'How is it going...',
        messageInQueue: 3,
        sentDate: '12/7',
    },
    {
        id: '9',
        userName: 'Phòng khám Aris Biu',
        userImg: images.user2,
        isOnline: true,
        lastSeen: 'Online',
        lastMessage: 'How is it going...',
        messageInQueue: 3,
        sentDate: '12/7',
    },
]
