apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor
  template:
    metadata:
      labels:
        app: doctor
    spec:
      containers:
        - name: doctor
          image: nguyenquangan318/doctor
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'clinic' 
            - name: MONGO_URI
              value: 'mongodb://doctor-mongo-srv:27017/doctor' 
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-srv
spec:
  selector:
    app: doctor
  ports:
    - name: doctor
      protocol: TCP
      port: 3000
      targetPort: 3000